### ISSUE TITLE
Display Wants and Offers on each member's profile page

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#100]
At the moment each member's profile looks like this:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/f495a835-aab4-44e6-9f25-f7a5103dad52)

It would be good to have sections that list their Wants and Offers.

**Comment by tfwoodroofMCS** [comment]
Description here was unclear - I think the intention was that other users should be able to see and respond to (e.g. add items to their cart as if they were in the Marketplace) the user's Wants and Offers by navigating to their profile on the membership list:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/6b334dfd-9658-48e3-a9a6-894af237dab6

Whereas the recent fix has Wants and Offers displayed to the user themselves under My account -> profile:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/45bc76df-3082-497c-b97f-9def946403c4

**Comment by yonasbek** [comment]
noted
