### ISSUE TITLE
Shopping cart appears to be very slow to respond not sure why

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#101]

**Comment by utunga** [comment]
Some discussino on the call - needs clarification really but lets 'make it like the notifications'

**Comment by tom-newman** [comment]
add loading component if poss

**Comment by tfwoodroofMCS** [comment]
Does seem to have improved, but still pretty slow - if I add an item from the Marketplace and then go straight to the Cart, the item isn't there. Typically appears when refreshing the Cart page after about 30 seconds, which is more than long enough to be uncertain as to whether it has worked.

**Comment by yonasbek** [comment]
Will be addressed in the next pr @tfwoodroofMCS

**Comment by tfwoodroofMCS** [comment]
@tom-newman to look at this after next PR.
