### ISSUE TITLE
CC-Server returns '500' errors when balance limits are exceeded or other situations, which causes problems for this app

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#102]
Generally speaking when a business rule is violated (or attempted) but the request itself is valid, REST systems tend to return http responses in the 4xx range - not the 5xx range. 

500 errors cause special 'exception handling' behavior - so for example an http-requests library that calls an end point and gets a 500 error will often throw an exception. So, for example in our javascript code we need to wrap that call with a try{} catch{} to capture the error condition. And even in the exception it can be hard to find the text that we want to pass on to the user.

A 4xx error like 'user not authorized' or 'balance exceeded' etc will often return an appropriate(ish) 4xx error (honestly it doesnt really matter which one as long its not 404 etc) and then include a *short* and simple text or json response that can be easily passed back to the end user. (Or wrapped with alternative explanations). 

But because cc-server+cc-node is returning 500 errors right now its causing us to find it hard to integrate.

**Comment by utunga** [comment]
Also it may be that sometimes what happens is that a condition is violated at cc-node which then throws an exception or a 500 error or something and then this causes cc-server to return a 500 http-response with no further information as to what the problem is.. or something

**Comment by yonasbek** [comment]
We got the the local cc-server up and running but one thing we faced is the permission violation so @utunga can you let us know how the cc-server is verifying the users because we are more or less stuck on that most of the requests we are sending are returning permission violation

**Comment by tfwoodroofMCS** [comment]
Changes from working with Matthew and Billy mean that 400 errors are now being returned, as expected.

Have to make sure that the deployed version of cc-server is the same as that being developed against.

Check if Matthew needs to add another tag to his code, then upgrade our server.

**Comment by utunga** [comment]
Server upgraded. This is good enough I think.

**Comment by utunga** [comment]
Upgraded to more recent versions lots of things got fixed. CC-server still occasionally sends a 500 in response to what I think should be a 4xx situation but its not holding us up anymore so closing.
