### ISSUE TITLE
Create a loading component to show if an action is loading.

### ISSUE THREAD

**Issue by yonasbek** [CredComSoc/CreditCoopTech#110]

**Comment by tfwoodroofMCS** [comment]
Nice feature! Works well if login credentials are correct.

However, if I enter invalid login credentials, the page hangs on the loading component and I have to refresh the page to get rid of it.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/11b8f7a7-1444-4997-87e4-bc0d67c2c502)

Suggested fix: close automatically after a second or two if login credentials are invalid.

**Comment by yonasbek** [comment]
ya found that issue will fix on the next pr
