### ISSUE TITLE
after hitting complete request on the shopping cart - the user should stay on cart page - for either success or failure

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#111]
Currently, when the user hits complete request, if the transaction succeeds, or fails it redirects to home page afterwards. 

![Image](https://user-images.githubusercontent.com/166867/264593544-2f582282-bb8e-4be5-9b2d-8da9774547bf.png)

It is especially confusing in the case of a failure that you get bounced to the home page - you see a pop up telling you there was a problem and then go to the home page. 

However even in the case of success I think its appropriate to show them a page with nothing on it. You bought all the things now your shopping cart is empty I think people like to see that to confirm it worked. 

So I think better to just keep them on the same page in either case.

**Comment by tfwoodroofMCS** [comment]
Currently redirects to cart if purchase request is blocked (which is consistent with above recommendation from @utunga), but if purchase request succeeds then redirects to home screen. This makes sense to me, but want to get @utunga's thoughts before marking as 'Done'.
