### ISSUE TITLE
Available Credit in yellow tab doesn't update if user with positive balance sells an item

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#115]
If a seller with a negative balance approves a purchase request (i.e. makes a sale), their Balance and Available Credit in the yellow tab, and in their Balance & limits section, both increase as expected (by 100 pollen in the example):

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/712ad09c-a2d5-46a4-b59d-85b0165d3c0d

However, if the seller has a positive balance, then although their Balance increases as expected (again, by 100 pollen in the example below), their Available Credit only updates in their Balance & limits section - it stays at 1000 in the yellow tab:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/cf3ab2c9-1910-4b78-980c-58f27069f8f7

This suggests that the Available Credit number displayed in the yellow tab either has a maximum value set to the magnitude of the user's negative credit limit (1000 pollen), or that there is some logic that displays either the magnitude of the negative credit limit if Balance is greater than zero, or Balance plus the magnitude of their negative limit if Balance is less than zero. Whichever explanation is true, this behaviour is inconsistent and confusing.

- [ ] Fix: make sure that Available Credit as displayed in the yellow tab is always calculated as the user's `balance` plus the magnitude of their `negative limit` (consistent with how it is always shown under Balance & limits, and in the message described in [this comment](https://github.com/CredComSoc/CreditCoopTech/issues/91#issue-1865237178) on #91).

**Comment by yonasbek** [comment]
@tfwoodroofMCS Like we discussed friday need more information on this.

**Comment by tfwoodroofMCS** [comment]
@yonasbek have just documented this more thoroughly, added a fix and moved to 'Backlog ready'.
