### ISSUE TITLE
Search all code for any remaining texts to be internationalised

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#119]
Do some kind of search (in English and Swedish) in the entire codebase for any remaining texts that need to be put through the internationalisation process.

Expect to find at least some in messages/notifications associated with transactions: see #86, #88, #89, #90, #91, #92, #103, #126.

**Comment by tfwoodroofMCS** [comment]
From Miles: 

this.$refs.addFile.innerText = 'Choose more'
Should use $t('choose_more') or similar.

Since we have it the old swedish text (for se.json) was as follows

this.$refs.addFile.innerText = 'Välj fler'

**Comment by EugeneJoe** [comment]
Need help on a couple of translations @tfwoodroofMCS :

- Ränta  på BSEK 
-  köparen har inte tillräckligt med bKr.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe the second one should be translated as 'the buyer does not have enough `credit unit`'.

It would be really useful if yourself and @yonasbek could work out what behaviour triggers this message, as it seems related to the balance limit functionality we've been carefully examining over the last few weeks.

With respect to the first one, we're going to ask what was intended in the original Svensk Barter app, as this one is very ambiguous.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe 'Ränta på BSEK' should be translated as 'Interest rate on negative balances'.

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS Alright.
I'll put in the fix for these two.
The whole FAQ section needs to be translated though.
It's almost all in Swedish.

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS that second message is in the Profile tab in the my trades section if the payer doesn't have enough credits

**Comment by tfwoodroofMCS** [comment]
Thanks @EugeneJoe - you probably saw I also gave some more details on the admin panel content in #72.

Don't worry about the FAQs or Members' Agreement for now - if the client wants them there at all, they'll have substantially different content to the Svensk Barter version.

Thanks for working out how to trigger the second message - let's discuss tomorrow.

**Comment by EugeneJoe** [comment]
@EugeneJoe 

- [ ] Put large blocks of text under one key rather than many short blocks
- [ ] use vue markdown to display the large blocks of text
- [ ] Put Placeholder text for FAQ section
