### ISSUE TITLE
Cart needs to display sellers associated with each item

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#123]
The notification that informs a user that a purchase request is invalid because it would take the seller beyond their positive credit limit identifies the seller (see #86). The user is then redirected to the cart (which is helpful), but the items shown there only give the item name, and not the seller:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/87c376d8-2b9c-405c-beb0-a62c9a54afb4)

It is therefore not immediately obvious which items need to be removed in order to unblock the transaction.

Suggested fix:

- [ ] Display seller name as well as item name and price.

**Comment by tfwoodroofMCS** [comment]
Weirdly this seems to have been fixed for test7:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/d048a399-404c-4066-8071-bbb2f08f7e8a)

But not for test11:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/83a0b5e8-59eb-4ae1-aa71-0717a7c81985)

This is also the case for test12 not displaying 'pollen' next to Pending Purchases, whereas it does for other users (see [this comment](url) on #125).

**Comment by yonasbek** [comment]
This is a very unusual behavior. A code that works for one use and doesn't for another user is very unlikely.

**Comment by tfwoodroofMCS** [comment]
Okay, let's not worry about it for now - I'll have a look again on Monday, and if needs be ask Miles to create some fresh users and test it with them.
