### ISSUE TITLE
Cart sometimes slow to update/appears to get confused

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#129]
For the most part the recent performance improvements have meant the cart functionality works very well. However, it sometimes seems to get stuck in a 'confused' state, or become quite laggy.

In the video below, the initial state is a 'Quantity' of 1 in the cart, but the yellow indicator reading 2, and the 'Total cost' at the bottom right reading '400 pollen' (should be 200, as per the 'Amount'). Increasing the 'Quantity' to 2 causes the 'Amount' to recalculate correctly, but the 'Total cost' to decrease to 200:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/08242541-6bf5-4e73-8d3d-46f5d5ea8fa6

It seems to be consistently 'in sync' from about 0:38-0:49, and then again from 1:06 to the end.

**Comment by yonasbek** [comment]
I think this is happening because the cart calculation have two source of data i have set it to just the backend so in the next pr it will be fixed

**Comment by tfwoodroofMCS** [comment]
Seems like this is still an issue:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/a0a5541a-49ad-4fdf-8d78-45fd3f5e1367

**Comment by tfwoodroofMCS** [comment]
@yonasbek - just noticed that the 'Total price' at the bottom right seems to be synchronised to the number of items in the cart. Since updating the cart is relatively slow, and the user's attention will actually be on the numbers under 'Units', 'Price/unit' and 'Price' in the centre of the screen, perhaps synchronising 'Total price' with these numbers (instead of the cart) would address this?

**Comment by yonasbek** [comment]
@tfwoodroofMCS @utunga The only remaining option i have on this is that when a user tries to add one item using the plus sign to cart or remove one item using the minus sign. it calls to the backend so for the data to make it consistent in each of the api calls i have to show the loading component so that the data will be consistent. other wise if the buttons are to be touched multiple times at once the data will have inconsistency like @tfwoodroofMCS explained. so any thoughts?

**Comment by utunga** [comment]
Hmm yeah i can see how this is problematic. 

First off this whole thing would be a lot easier if the whole shopping cart was kept client side - like most people do - but perhaps that is too big a change? I don't see it as an important feature (or even a good feature) that if you close your browser and come back on a different day it still knows what was in your shopping cart. 

I am assuming that re-writing the shopping cart to be kept in the state client side only is too big a change at this point. There is an issue about this one already -- #118. If you think 118 is not too bad then maybe we just do that - but I'm assuming it would be a lot of work. 

Failing that, I gusss the other thing that people sometimes do in a situation like this is:

**When user makes action on client side (eg clicking plus or minus):**
1 - Immediately update state client side
    1.1 .. which updates UX (what user sees) 
2 - Post the action / update to the server 
3 - When the state is updated on the server (and various business logic takes place) 
     a notification is sent back to the client 
     3.1 .. this updates the state on the client side
     3.2 .. which in turn updates the UX 

Done right (i.e. leveraging the framework for state management) the coder doesn't have to do that much work as the state handling happens mostly in the framework. Depends a bit on how things are wired up though. Ideally all the user has to do i connect up a thing to update state and post data back to server, and then a thing that updates the UX based on $state whenever it changes in a 'reactive' way.

Of course the downside is that if the server side state update and the client side update conflict with each other then
 (a) the server side update should overwrite the client side one
 (b) this can take a second so the user would see a change then a sort of *glitch* then the state would update again. 
 
 98% of the time though, in theory, the server side logic would do the same as what happens in the backend so the user doesn't noticed anything.

Back in the world of what you have in place here is it possible to just update the $state locally first, before sending the post to the server?

**Comment by tfwoodroofMCS** [comment]
This is now super reliable and responsive - great job @yonasbek!
