### ISSUE TITLE
Revise wording on New Item flow to cover 'wants' as well as 'offers'

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#13]
When adding a 'Want' on the New article page, the required information on the second page is confusing: it asks for a Time ('Until when will this product be available?'), Place ('Location of product') and Price ('What is the price of the product').

These fields should be revised to be appropriate for someone posting a Want. See also #17.

![signal-2023-07-14-124859](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/12b393a7-8262-4f72-b75d-23fc05da2174)

**Comment by tfwoodroofMCS** [comment]
The field under 'Time' now reads 'When do you need this item / until when will it be available', which addresses both Needs [now Wants] and Offers. However, 'available' (at least on my device) is cut off so that it just reads 'avail'. Suggest 'When do you want this / until when will it be available' (also addresses that 'item' doesn't correspond well to the 'Service' option).

The 'Indefinitely' check box should read 'Whenever available'.

Under 'Place', I think 'Location of product' should be changed to 'Location where product will be used'. As far as I can see delivery or collection have to be negotiated/arranged separately, perhaps in the chat. This should be made clear, or perhaps we need to have a whole new issue so that there are options to include this in the price?

'Location of service' should be changed to 'Location where service is to be performed', and the dropdown should include a 'Remote' option (which should also be applied to the Offers flow).

Under 'Price', the text should read 'What is the price you are looking to pay?'

**Comment by utunga** [comment]
I agree, good ideas for wording @tfwoodroofMCS

**Comment by tfwoodroofMCS** [comment]
Mostly fine, except:

- [ ] If creating an Offer, then the checkbox under Time now reads 'Whenever available.' This is correct for a Want, but should have remained as 'Indefinitely' for all Offers.
- [ ] For an Offer + Product combination, the placeholder text under Place needs to be changed from 'Location where product is wanted' to 'Location of product'.
- [ ] For all Services (Wants and Offers), there should be 'Anywhere' and 'Remote' options in the Place dropdown.
