### ISSUE TITLE
Check functionality and update message when attempting to make purchase requests beyond actually available credit

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#130]
Buyers are blocked from making requests that would take their balance as it is when the request is made below their negative limit (see #91). However, because the buyer's balance _as displayed_ doesn't actually update until their requests are approved, it might occur to them to attempt to accumulate purchase requests which (if completed) would collectively take them below their negative limit.

In practice, this also appears to be blocked, which is the correct behaviour. From frontend testing, what seems to happen is that there is some kind of 'actually available credit' (not currently visible to the user) which keeps score of their displayed balance minus any outstanding purchase requests. If they attempt to make purchase requests that would take this number below their negative credit limit, they get the following message:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/20376931-af10-479f-8c86-6787bdd6f00e)

 - [x] Testing from the frontend suggests that this functionality is working as expected and is triggered correctly. However, this should be looked at from the backend to verify.
 - [x] Update the pop-up header to read 'Insufficient credit'.
 - [x] Update the pop-up main text to read 'You do not have enough credit to request this purchase, as the total price is `total price` `credit unit` and your available credit (including other outstanding purchase requests) is `actually available credit` `credit unit`.'
 - [ ] We should consider displaying the 'actually available credit' to the user.

`actually available credit` should be calculated as `balance` minus `total price of other outstanding purchase requests` plus the magnitude of their `negative limit`.

**Comment by tfwoodroofMCS** [comment]
Still seeing the behaviour as described in the issue - not sure this is ready for review?

**Comment by tfwoodroofMCS** [comment]
To reproduce:

- Log in as testuser5, who has a balance of -350 pollen.
- Add 1 unit of test9item (400 pollen) to cart, but don't make the purchase request. Verify that it is displayed in Pending Purchases. Visible balance remains at -350 pollen, but 'actually available credit' is now -750 pollen.
- Add 3 units of test6item (300 pollen) to cart, and make the purchase request. This would take 'actually available credit' to -1050 pollen (i.e. below -1000 pollen) and so should be blocked, but the message displayed is still the one shown in the original issue description.

**Comment by yonasbek** [comment]
i am sorry this may be my issue but i am getting this. 
![image](https://github.com/CredComSoc/CreditCoopTech/assets/49316951/604b7ab8-3871-4be3-93da-70fc698a33a9)

**Comment by tfwoodroofMCS** [comment]
That's because you're trying to make a single purchase request with all the items in the cart, triggering the 'negative limit violation' behaviour immediately.

For this issue, the idea is that the user might make a series of separate purchase requests. I've just looked back at my instructions to reproduce, and realised that they're wrong - the second step says *not* to complete the purchase request for the first item, but actually the request does need to be completed - apologies. I've gone back and edited - have another go!

**Comment by tfwoodroofMCS** [comment]
This now seems to be enforced incorrectly - in the video, the user has a Balance of -300 pollen plus an outstanding purchase request for 400 pollen, so should still to able to make further purchase requests for up to 300 pollen. However, a request for 300 pollen is blocked:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/5e494c4f-516c-4f00-86c0-6aac8cd504b5

A request for 400 pollen is correctly blocked, and a request for 200 pollen is correctly progressed. Perhaps there's 'less than' logic where there should be 'less than or equal to'?

**Comment by tfwoodroofMCS** [comment]
Wouldn't removing the operators completely stop the functionality working?

**Comment by yonasbek** [comment]
no just remove the equals operator then the logic will be to check if the balance is only less.

**Comment by tfwoodroofMCS** [comment]
Additional minor comment: in the message main text, the minus sign before the second instance of the 300 pollen need to be removed, as should the word 'actually'.
