### ISSUE TITLE
Check functionality and add notification for cancelled purchase requests

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#131]
If a user creates a purchase request, it appears under My account -> Trades -> Pending Purchases, where they have an option to cancel it. This appears to work as expected - the request's status is updated to 'cancelled' and their visible balance doesn't change.

However, as per #130, there also appears to be an 'actually available credit' variable that is not currently visible to the user, but which ensures their (visible) balance minus the total price of their outstanding purchase requests doesn't violate their negative credit limit. The backend functionality should be checked to verify that this actually available credit is restored to what it was before the now-cancelled purchase request was made.

The purchase request also disappears the seller's Purchase requests, which is good. However, the seller should also get a notification with the text '`buyer username` has cancelled their purchase request for `item name`'.

**Comment by yonasbek** [comment]
@tfwoodroofMCS In this issue the user's credit or doesn't increase or decrease while the request is in pending. So this task would be to create a notification to the seller when the buyer cancel's the transaction.

**Comment by tfwoodroofMCS** [comment]
Yes, exactly!

**Comment by tfwoodroofMCS** [comment]
Just tested between test11 (buyer) and test12 (seller) and test12 didn't receive a notification when test11 cancels their purchase request.

**Comment by tfwoodroofMCS** [comment]
All working fine with 14 & 15 - as with some other fixes, seems to have been a problem with 11 & 12.
