### ISSUE TITLE
http response messages (coming from the server) should probably? be internationalized

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#134]
There are now a few places in the server side code with text in English that used to be in Swedish. This includes http status (or error) codes that are only expected to be seen by programmers. 

Since we don't have a server side internationalisation framework installed it is not as easy to fix these ones. 

Since this is for programmers it's might just be OK not to internationalize the http-status codes and just do them in English.

Nevertheless just to capture them, here's the status codes along with their Swedish translations - while we have them. In case we want to go back and tidy this up. 

```
res.status(404).send('Det gick inte att skicka e-postmeddelandet till denna medlemmen')
res.status(404).send('Email could not be sent to this member.')

res.status(200).send('Den nya medlemmen är nu registrerad!')
res.status(200).send('The new member is now registered!')

res.sendStatus(404).send('Det gick inte att registrera medlemmen.')
res.sendStatus(404).send('The new member could not be registered.')

res.status(500).send('Denhär medlemmen finns redan.')
res.status(500).send('This member already exists.')
```

There are two more ones with out Swedish translations we might want to look at as well.

```
res.status(404).send("The file does not exists.")

res.status(404).send("The profile does not exist.")
```

This might not be a complete list but thought I'd capture this while we have it.

**Comment by tfwoodroofMCS** [comment]
- [ ] @EugeneJoe to do a sweep and double check no instances of Swedish in backend, replace any with hard-coded English.
