### ISSUE TITLE
Email text should be either in a CMS or Internationalized

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#135]
Since the email sending code is on the server it's not easy to re-use our vue-i18n internationalization framework to handle these.

Nevertheless thought I'd capture these while we have them fresh in memory. 

The first one is the "**Welcome**" email text. Which is currently hard-coded in English (and hard coded to Land Care Trade) [here](https://github.com/CredComSoc/CreditCoopTech/blob/0b577a3535847daa39cd952f1502f3a8ae376621/backend/routes/index.js#L444)

The other two are the **"Reset your password"** and "**password updated**" emails. Which is similarly hard coded in English / for Land Care Trade [here](https://github.com/CredComSoc/CreditCoopTech/blob/0b577a3535847daa39cd952f1502f3a8ae376621/backend/routes/index.js#L1211) and [here](https://github.com/CredComSoc/CreditCoopTech/blob/0b577a3535847daa39cd952f1502f3a8ae376621/backend/routes/index.js#L1244) 

It's not easy to fix either of these but noting them down along with their Swedish translations while we have them in case we need to make the site work in Swedish again.

```
subject: 'Medlem i Svensk Barter', // Subject line
subject: 'Welcome to Land Care Trade', // Subject line
text: `
Du får det här mailet för att du har begärt att vara medlem hos Svensk Barter.
Vänligen klicka på följande länk eller klistra in den i en webbläsare för att slutföra processen:

You are receiving this email because you have requested to join Land Care Trade.
Please click the following link or paste it into a browser to complete the sign up process:
${FRONTEND_URL}/login
Dina inloggningsuppgifter är:
E-postaddress: ${newPro.email}
Lösenord: ${newPro.password}
Your login details are:
Email address: ${newPro.email}
Password: ${newPro.password}

Med vänliga hälsningar,
Svensk Barter
Best wishes,
Land Care Trade
```

```
from: ouremail, // sender address   ???'svenskbarter.reset@outlook.com'???
to: user.email, // list of receivers
subject: 'Återställning av lösenord', // Subject line
subject: 'Reset your password for Land Care Trade', // Subject line
text: `
Du får det här mailet för att du (eller någon annan) har begärt att ditt lösenord hos Svensk Barter ska återställas.
Vänligen klicka på följande länk eller klistra in den i en webbläsare för att slutföra processen:

You have received this email because you (or someone else) has requested that the password associated with this email address at Land Care Trade be reset.
Please click the following link or paste it into your browser to complete the process:


Om du inte har begärt detta, vänligen ignorera detta mail så kommer ditt lösenord förbli oförändrat.
If you have not requested this reset, please ignore this email and your password will remain unchanged.
```

```
to: user.email,
from: ouremail, //'svenskbarter.reset@outlook.com'
subject: 'Ditt lösenord har ändrats',
subject: 'Your password for Land Care Trade has been updated',
text: `
Det här är en bekräftelse på att lösenordet för ditt konto "${user.profile.accountName}" hos Svensk Barter har ändrats.
This is a confirmation that the password for your account ${user.profile.accountName} with Land Care Trade has updated".
```

**Comment by tfwoodroofMCS** [comment]
- [ ] @EugeneJoe to internationalise all three emails (welcome, password reset, password reset confirmation) by using markdown in .json and vue library found by @utunga to render markdown into html or rich text as needed.

**Comment by EugeneJoe** [comment]
- [ ] markdown to html converter that converts the template to html and chucks it into email body.

**Comment by tfwoodroofMCS** [comment]
- [ ] Eugene to set environment variables so that emails can be tested on staging.
- [ ] Dil to check where/how support emails for LCT are being sent.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - just tried to generate a password reset email from staging version of LCT, and the site is hanging:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/b6593d12-d79d-4a78-92e9-3175b79463d8)

Has been doing this for about 5 minutes, so longer than expected even given the very sluggish server. Any ideas about how to resolve so that I can test?
