### ISSUE TITLE
Upgrade cc-server in production

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#139]
cc-node and ccphplib both have 0.8.0 tag, but need Matthew to create a tag for new versions.

We expect that cc-server should have the same tag, but at present they isn't tagged at all. 

Then need to actually upgrade on production server.

Fixing this will also fix
- #102
- #94

**Comment by utunga** [comment]
@tfwoodroofMCS I am confident cc-server has been upgraded - and since you have tested and closed the bug that verifies that it has in fact been upgraded, I think I'm gonna close this one also.
