### ISSUE TITLE
Fixes to calendar events

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#146]
A number of issues with creating events via the calendar:

**General**:
- [x] Not saving events on the backend it is saving locally let it save in the backend.
- [x] Currently possible to have an event with an end time before the start time. Create logic and notification that blocks this.
- [x] Not currently possible to have events that last for multiple days: add functionality for this.
- [ ] Add functionality to make events recurring.
- [ ]  Can't edit events: add functionality for this.
- [x] Can't delete events: add functionality for this.
- [ ] Add functionality to invite guests via email (only if not too difficult).

**Pop-up on first event creation**

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/14f25e4e-d685-4831-9ffe-2794d0f09588)

- [x] Contact and description fields are pre-filled with variable names, rather than human-readable text. Replace with 'Contact' and 'Description' respectively.
- [x] Replace 'event.contact' contact header field with 'Contact details'
- [x] Change placeholder text in Event location field from 'Plats' to 'Place'

**Pop-up on subsequent event creation**

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/b91ddb7a-9835-4534-ac6c-75c41e59ba38)

- [x] After creating a first event, the pop-up is populated with its details for subsequent events. These fields need to be reset with the original placeholder text.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe: @yonasbek is going to start working on this soon, which will probably result in some more things to be internationalised.

**Comment by tfwoodroofMCS** [comment]
App hanging after invalid time now fixed, but redirects to home - change so that it redirects to events/calendar.

**Comment by tfwoodroofMCS** [comment]
Deleted events don't disappear until page is refreshed - possible to make them disappear immediately?

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/24cda998-db26-4024-8a9c-bdf7462b8142

**Comment by tfwoodroofMCS** [comment]
Editing events causes them to disappear!

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/c18b763d-6b5a-4d27-83b6-9869d529a49d

**Comment by tfwoodroofMCS** [comment]
To make it clearer when the event is, replace the 'a' after the time with 'am', and the 'p' with 'pm'.

**Comment by tfwoodroofMCS** [comment]
Considerably better than it was, but still not really functional. Not a priority to fix, but listing observed issues here for future reference:

- [ ] Some bits of calendar sometimes freeze (e.g. buttons navigate to next or previous month, month/week/day buttons) after creating/editing/deleting events. Have to refresh page (even this doesn't always work).
- [ ] When creating an event with an invalid time range (i.e. event ends before it finishes), an error pop-up appears, but the event is still created.
- [ ] When editing the event times, the start time as displayed in the main calendar view is not updated from the original.
- [ ] Have to refresh page in order for deleted events to disappear.
- [ ] To make it clearer when the event is, replace the 'a' after the time with 'am', and the 'p' with 'pm'.

**Comment by yonasbek** [comment]
The first issue may be due to our server in the rendor. Because it is working for me locally and in the production one. But will investigate.
The third topic need more explanation.

**Comment by tfwoodroofMCS** [comment]
Third topic: in the video below, an event is created to start at 11:30, but editing it to start at 11:45 does not result in the modification being displayed:

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/2e8ca740-e6a5-442f-9f67-0796e742e1e4

Everything else working well, so calendar is now useable - nice one!
