### ISSUE TITLE
Item in 'purchase requests' for selling user doesn't show up in 'pending purchases' for the buying user

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#160]
The user on the left is testuser2, the user on the right is testuser3. 

![Image](https://user-images.githubusercontent.com/166867/269266262-fe0bf4cb-04cd-43d1-a564-97b20e96b152.png)

As you can see testuser2 has a purhcase request from testuser3 

But testuser3 doesn't see this in 'pending purchases'.. seems to me they probably should?

**Comment by utunga** [comment]
@tfwoodroofMCS  is that right? Is this a bug?

**Comment by utunga** [comment]
BTW you can't see which user is which but trust me I checked... actually you don't have to trust me on that.. user profile pages per below: 



![Image](https://github.com/CredComSoc/CreditCoopTech/assets/166867/53531baf-0945-4141-b78f-bdfc4190d89d)

**Comment by utunga** [comment]
Maybe this is because of messed up users though - sorry my bad I shouldn't be using these users hey

**Comment by tfwoodroofMCS** [comment]
Immediate reaction would be that these test users are known to have weird behaviour, and I haven't noticed this myself, but will check later today with other users.

**Comment by tfwoodroofMCS** [comment]
Just checked with testuser and test2user (post database clear-out) and working correctly, so closing this issue.
