### ISSUE TITLE
Remove ability to edit other users' Wants

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#211]
https://github.com/CredComSoc/CreditCoopTech/assets/105865183/9425a960-fa17-464d-8af1-d9a484bd75c7

**Comment by EugeneJoe** [comment]
On this, do we want the "Start Chat" feature on both wants and offers from other users or do I leave it as is @tfwoodroofMCS

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - good spot. We probably do want the Start chat feature on both wants and offers, but I'll make a separate issue for this as it's a low priority.
