### ISSUE TITLE
Not all Shop items can be bought/sold

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#23]
Can we check that this is not due to trying to buy something posted by the logged in user? Does the shop show all items (even ones the logged in user posted).

Although this Shop item can be added to the Cart:

![signal-2023-07-14-151923](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/d5eada28-c2c5-45b1-b68c-49119a0ec93a)

This doesn't appear to appear as an option for the other items:

![signal-2023-07-14-151947](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/944b5668-a5ec-42ca-9a97-2c4048d4a597)

**Comment by tom-newman** [comment]
Could be because this is an item posted by the user you were logged in as - suggested fix is to display an edit item button here, once that screen is available.

**Comment by EugeneJoe** [comment]
Add "Edit" button in place of "Add to Cart" as well as add a "Delete" button.
