### ISSUE TITLE
Update item categories and images

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#255]
The staging version of Svensk Barter currently uses the item categories and images associated with Land Care Trade:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/35ccecc0-8b2e-4c34-b5d8-050994fdebbe)

The categories need to be replaced with those used on the production version of Svensk Barter, and corresponding images found.

**Comment by tfwoodroofMCS** [comment]
- [ ] @tfwoodroofMCS to get categories from deployed version and ask Jonas for default images.

**Comment by EugeneJoe** [comment]
Same issue here.
They're sharing the same database so they're showing the same data

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - I've just logged into LCT staging and SB staging and they're both showing different categories (see the New Item workflow), as intended.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - we've just realised that at the moment it's not possible to delete categories (via the admin panel) that are in use for user-created items (which is sensible), but this does make it urgent that we are able to edit existing categories (i.e. change the name and add/update images, again via the admin panel) without breaking links to user-published items. Might you be able to prioritise adding this functionality?

**Comment by tfwoodroofMCS** [comment]
Just tested editing categories (name and adding images) and it works well - good job @EugeneJoe.

It seems though that if the category image is changed, items previously created keep the old image. It would be good if they were updated, but @dilgreen I'm guessing that can wait - it might take Jonas a while to choose a new set of default images in any case?
