### ISSUE TITLE
Minor text edits

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#26]
List of very minor text edits for consistency of formatting:

- New Article flow: on the first page, capitalise the first letters in ‘item type’ and ‘product’ & ‘service’ in the associated dropdown, and the ‘next’ buttons on all pages in the flow.
- Capitalisation of ‘close’ in item popup in Shop.
- Capitalisation of ‘success’ in item added to cart popup.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - in addition to ticking off the remaining ones, please could you check that all texts associated with those that have already been ticked have been put through the internationalisation process?

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS this one is a bit confusing

`
When editing an item, the pre-filled section under 'Want or Offer?' sometimes has 'buying' (this applies to an item posted early summer, but not for one posted end August, which has 'want', as expected, so may not need fixing).
`

**Comment by tfwoodroofMCS** [comment]
Okay, ignore that one for now as I haven't seen it lately.

**Comment by EugeneJoe** [comment]
@tfwoodroofMCS text is too long on this one.

Messes up the layout.
Do you have a shorter suggestion?

**Comment by tfwoodroofMCS** [comment]
Sorry, which one?

**Comment by EugeneJoe** [comment]
...f 'MEMBERS' to 'Find and connect to other Land Care Traders.'

This one

**Comment by tfwoodroofMCS** [comment]
Ah okay - hopefully 'Find and connect to other traders.' will fit.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - just spotted another one - 'adress' on My account -> Profile -> Street address needs to be changed to 'address'.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/ee728221-f0f8-4ab3-b847-e8eb6ae390d8)

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - just reviewed this and pretty much all done - thanks. However, there are a few that still need further work - I've unchecked them, moved them to the bottom and added comments after 'UPDATE'.

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe - have just checked again and some of these are still outstanding - slightly confused as to why they were checked off (unless you've got an upcoming PR that addresses them).
