### ISSUE TITLE
Editing a shop item

### ISSUE THREAD

**Issue by dilgreen** [CredComSoc/CreditCoopTech#30]
Currently, the app does not allow editing of an existing shop item.

This was justified by the original designers on the basis that shop items are considered Stock Keeping Units, which should be specific, not susceptible to change over time, as this might disrupt stock-keeping or accounting practice.

This is considered too restrictive here - even a typo cannot be corrected

[here I am trying to use the MongoDB terminology - where SQL has 'tables' and 'rows', Mongo has 'collections' and 'documents']

- [ ] Investigate whether the app - in its balance calculations or other reporting - does any calculations / filters based on attributes of the shop items (documents in the 'posts' collection), and describe here:
   - _things the app does with post document attributes_

- [ ] Propose approaches here:
    - Quick and dirty A: 
        - instead of editing and existing shop 'document', and ;edit' button gets the data from the selected existing shop item document, then starts a 'new item' workflow, with all fields prefilled. The user can now edit everything. When they publish the altered item, the original will no longer be shown in the shop.
        - This method would also make it easy to add a 'duplicate' button - same workflow, but without hiding the original item
   - Quick and dirty B:
       - If considered 'safe', just allow editing of existing items

**Comment by EugeneJoe** [comment]
I think it should be alright to edit items.
I've yet to see how editing an item would affect price calculations or anything of that sort.
@utunga any contrary thoughts?

If not, I'll set up an endpoint to edit items.
