### ISSUE TITLE
Categories and their images

### ISSUE THREAD

**Issue by EugeneJoe** [CredComSoc/CreditCoopTech#33]
Create a categories table on the backend and store each category as well as a default image for that category to be used when the user doesn't upload an image for an item.

Post discussion with Yonas.

Implement with:

- new table/collection in Mongo - Categories
   - Category UUID
   - Category name
   - Category image stored here
   - Category 'live' flag (so that categories can be retired/drafted, different sets in different instances)

[This file](https://docs.google.com/spreadsheets/d/1NaX7mMZyLN3rR5d2XQnJZC_2G7-yROqxxixM6Qcnv7o/edit?usp=sharing) has current category names and links to standard category images

I don't think we need to worry about internationalisation of these - setup/admin of each instance can add the categories they want into the mongodb.

**Comment by tfwoodroofMCS** [comment]
Looked at this 18th August and although the categories list appears as per the spreadsheet, adding default images doesn't appear to have been implemented.

**Comment by tfwoodroofMCS** [comment]
Since my comment above is being addressed by #73, moving this to 'Done'.
