### ISSUE TITLE
Switch language to "wants"/"offers" and "marketplace"

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#41]

**Comment by yonasbek** [comment]
More Description in this issue?

**Comment by utunga** [comment]
Hi @yonasbek ,.. hopefully this can clear things up a bit 

- Currently where we have 'selling' it should be 'offer'. or 'offers'

- Currently where have purchase, buy or similar to should be 'want' or 'wants'. 

- Currently the 'shop' is called shop, but we should rename this to 'marketplace'. 

For instance "My sales & purchases" should be changed to "My wants & offers"

--

Also anywhere it still says 'Article, "Articles" or "Posts" should be replaced with "Item" or "Items". 

--

Don't get this confused with  'products' and 'services'.  We are gonna keep the distinction here. So for example you coul dhave an item that is a 'want' for a 'service' or a 'offer' of a 'product' or any other combination. However products and services might be less prominent.  

On the home page where it has the 'Shop'

<img width="1020" alt="image" src="https://github.com/CredComSoc/CreditCoopTech/assets/166867/ec2b3294-1a8b-4ea1-acc8-1f5152fc5e84">

 it should say 

"Marketplace

Browse the most recent wants and offers."

--

If we change sell/buy in the code to 'offer/want' it is likely to have effects in terms of queries to the (mongodb) database. For instance all items might disappear from search and in various other places. 

That's OK - either we just accept this and know that we have to repopulate our database, or, better,  we write a migration script that converts and maybe copies data from the 'posts' namespace to the 'items' namespace. 

Changing the internal code names as well as the front end visible names of these things is somewhat optional but I'd err on the side of changing these things now, while we can - so that things are easier to understand.

**Comment by utunga** [comment]
Also whereever it says "need" it should say "want"

**Comment by yonasbek** [comment]
I have created a pr with it and instead of updating the data base or writing scripts I added an an alternative or parameter in the if statements that filter based on the code.

**Comment by utunga** [comment]
OK that's fine. See my comment on the PR but I guess this is OK long as we try to remember to remove the extra check later is all

**Comment by tfwoodroofMCS** [comment]
On the My account page, one of the subsections is 'Item'. Should this be changed to 'Offers' in order to be consistent with the above?

**Comment by tfwoodroofMCS** [comment]
Also related: one of the other subsections is 'Wants', but this contains information on purchases, so if it got caught in a dragnet should probably be reverted to 'Purchases'.

**Comment by tfwoodroofMCS** [comment]
Another one: when following the New item workflow (in this instance a Need), the confirmation pop-up uses 'Item' and 'shop'.

**Comment by tfwoodroofMCS** [comment]
When editing an item, the pre-filled section under 'Want or Offer?' sometimes has 'buying' (this applies to an item I posted a couple of months ago, but not for one I posted today, which has 'want', so may not be an issue).
