### ISSUE TITLE
Containerize CC-Node dependency

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#42]

**Comment by utunga** [comment]
_Creating as an issue in this project instead of https://gitlab.com/credit-commons/cc-node because its easier to track here (but of course this could go in either place)_

## Discussion

We have a hard time getting new developers on board with the project, and one of the most common reasons is that we have to depend on the ledger service (aka cc-node aka credit commons protocol) service, which is not currently super easy to set up. It's an ideal dependency to containerize or 'nixify' in some way. For local development of *this* app we don't want to actually develop in php or even really make changes to the cc-node especially, we're just using it as an api dependency. 


*Architecture diagram* 

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/166867/87270cbe-c8f5-4776-8491-28492e318bb0)

As you can see, from the above the existing 


Also worth noting that, as it stands the mongo-db database used for the project's 'back end' and the mysql database behind cc-node need to be kept 'in sync' for the app to work. That is, while it is true they are separated, it is not 100% cleanly. Specifically the userId guids (and probably some other info) need to match perfectly between the two databases for the app to be have in a sensible way. This means that essentially for development you want to start with two empty databases and then populate some test/play data from there, using the app. 

## Acceptance Criteria 

- Developers can easily have a specific version of cc-node running locally. 
- The cc-node app would expose a CC-Node in REST interface at a specific port eg http://localhost:8987 
- It's easy to go from clean/ empty development stack to a working service. After installing a minimum number of dependencies (eg installing docker or installing some nix framework bits) it is possible to install and setup the service to run locally with one command line 
- It is possible to have the CC-Node service run in a 'set it and forget it' way - that is, starting up on startup. 
- Clear documentation explains how to do this and that documentation is made accessible/ part of the CONTRIBUTING.md installation instructions
- This works for developers on Mac OSX and  Linux  (Windows support is a 'nice to have')
- It is possible to know what exact version of cc-node is installed via this method 
- It is possible for someone experienced with the relevant tooling to update or add another image file with the latest version(s) of cc-node so that people can easily upgrade.

**Comment by utunga** [comment]
It would certainly be nice to containerize or nixify the whole process of setting up a development instance of this app. Once we have the cc-node bits sorted perhaps we can look into the pros and cons of building an image for the rest of it.

**Comment by utunga** [comment]
Forwarded message (from Telegram) 

> I just pushed my modified cc-server repo here if you want to check it:
https://gitlab.com/bu6n/cc-server/-/tree/docker-and-small-changes/.docker

> It's a network of 3 nodes, with account stores in a .json file and init SQL scripts for the database. It's not up-to-date with the latest commits from @matslats and I haven't documented it now. But if you do composer install in the root folder then docker compose up in the .docker folder, it "should" work :)

**Comment by utunga** [comment]
We agreed that (as part of this card) we would make sure to **document** 
- the process for building, configuring and running the docker locally (in dev)
- document, also, the steps we would need to deploy cc-server to production
   - what tag we need to pull from gitlab/cc-server gitlab/cc-node via `composer` and how
   - what series of manual steps is needed to copy various files (eg workflow.json, node.ini) into place
   - any other configuration needed in production

This documentation should go into [INSTALLATION.md](https://github.com/CredComSoc/CreditCoopTech/blob/main/INSTALLATION.md) and can be approved as part of the same PR.

Also we should check in the actual configuration files we want to use (workflow, node.ini, etc) as well as the Dockerfile and any docker-compose json etc etc into this repo here. 

All these steps will be verified as part of the review on this card. @utunga will likely be in a position to run through the full installation on a clean machine soon and so can verify that it all works then

**Comment by tfwoodroofMCS** [comment]
Also, INSTALLATION.MD says 'Ensure you've set your CC_NODE_URL to localhost:8000 to connect to the locally-running version of cc-server'. Doing a global search in the code for 'CC_NODE_URL' results in 24 results across multiple files - please could you specify exactly how/where to do this?

**Comment by utunga** [comment]
You set the CC_NODE_URL in the .env file.. which is in GitHub but you can
override for your particular situation
