### ISSUE TITLE
Clicking on the user.financialOverview button in the back end causes server to crash

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#46]
This button is the problem 

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/166867/789f98e1-52f9-462c-bdab-ceae468adb38)

**Comment by yonasbek** [comment]
This has two issues both the button in the front end crashes the front end server and the api call it calls crashes the backend server. I will address both.

**Comment by utunga** [comment]
LOL !
