### ISSUE TITLE
Photo upload size limit is frustrating

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#66]
When trying to upload an image, the file size limit of 2 MB seems too restrictive (my phone is more than 5 years old and doesn't have a particularly good camera, but I still couldn't take any photos that were within the limit).

**Comment by utunga** [comment]
I've changed this from 'size limit is too small' to 'size limit is frustrating'. 

- It absolutely should be possible to take a photo with a normal phone and then use it as a category image
- On the other hand we don't want large images being inserted into the database/used as content.

Basically current/modern phone cameras create images that are too big to use in a web application.

To fix this we may need to do some auto-compression or similar and then loosen off the file upload limit
