### ISSUE TITLE
Subsections on My account page have incoherent names and content

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#67]
On the My account page, there are four subsections ('Profile', 'Wants', 'Item', 'Needs'). 'Needs' duplicates the 'Profile' information, but should probably be changed to 'Wants' and the content updated accordingly. The current 'Wants' section has content that is more like a list of purchases - see also https://github.com/CredComSoc/CreditCoopTech/issues/41#issuecomment-1684233183 and https://github.com/CredComSoc/CreditCoopTech/issues/41#issuecomment-1684236969.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/2af0b426-530f-4230-90c7-ebc55cb10819)

On desktop view, it looks different: 'My Wants and Offers' (equivalent to 'Wants') also contains purchase information, 'Item' is rendered as 'My items', and there is a 'Balance & limits' section (presumably equivalent to the non-functioning 'Needs' seen on mobile).

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/0c128158-8074-41c8-a0de-d722aa7d8408)

**Comment by yonasbek** [comment]
The desktop version has the correct implementation so i will change the mobile view to the desktop one

**Comment by utunga** [comment]
Let's rename "my wants and offers" to "my trades" in the desktop view 

And in mobile view 

"profile", "trades", "items", "balance"

**Comment by tfwoodroofMCS** [comment]
Looking good!
