### ISSUE TITLE
Sort out the last of the Swedish 

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#7]
Swedish remaining in the app:-

- [x]  Failed login produces advice message in Swedish: '_Fel epost eller lösenord_'. Replace with 'Invalid email or password'
- [x] In the New Item workflow, instead of 'Next', '_Nästa_' sometimes appears  [can't reproduce this consistently. Weirdly, refreshing the page sometimes makes it switch].
- [x] Under My account -> Profile -> Edit, above the profile picture, we see: '_Logotyp_'. Remove this, or if this is difficult replace with 'Profile picture'.
- [x] Some notifications produce: '_har godkännt din köpförfrågen_', which should read 'has approved your purchase request'.
- [x] New chat message notification reads '[username] have _sentett chatt-meddelande_.', which should read 'sent a chat message'. Also, 'have' should be 'has'. 
- [x] After uploading one image in New item workflow, grey button changes to '_Välj fler_', which should be 'Choose more' (see #79 for a screenshot).
- [x] In backend/routes/index.js:
*** Line 467: change 'Det gick inte att skicka e-postmeddelandet till denna medlemmen' to 'Email could not be sent to this member.'
*** Line 472: change 'Den nya medlemmen är nu registrerad!' to 'The new member is now registered!'
*** Line 475: change 'Det gick inte att registrera medlemmen.' to 'The member could not be registered.'
*** Line 480: change 'Denhär medlemmen finns redan.' to 'This member already exists.'

**Comment by utunga** [comment]
let's use `#TODO_SWEDISH` as a tag to mark any that we see in the code @

**Comment by tfwoodroofMCS** [comment]
Creating a comment to flag all instances of Swedish I came across when bug hunting today:

- 'Nästa' sometimes appears instead of 'Next' in the New Item workflow, but I can't reproduce this consistently. Weirdly, refreshing the page sometimes makes it switch.
- Under My account -> Profile -> Edit, 'Logotyp' appears above the profile picture.
- 'har godkännt din köpförfrågen' in some notifications.

**Comment by dilgreen** [comment]
Issue content needs to live in the description, rather than comments, where it will likely be missed / unclear as to whether it is a required action for the issue.
I've put the content of the previous comment into the descfription.

**Comment by yonasbek** [comment]
On Backend in index.js line 468 an email is being sent in another language may be swedish

**Comment by tfwoodroofMCS** [comment]
@EugeneJoe have just updated the checklist in the main body of the issue with translations.
