### ISSUE TITLE
Item availability field is hard to use in general, editing item with indefinite availability results in annoying error,

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#70]
If an item is created with 'indefinite' availability and then edited, the preloaded date range changes to _current date - current date_, which then throws an 'invalid date' error.

**Comment by utunga** [comment]
Item availability field in general is very hard to understand - needs to be fixed up in lots of ways

**Comment by utunga** [comment]
From the other issue:

When creating/editing an item with finite availability, clicking on the date range causes it to display dd/mm/yyyy and appear to become unresponsive to further clicking. In this state, it is only possible to proceed if the item is being edited (and therefore already has a date). It's not obvious that it's necessary to click on the tiny calendar icon.

**Comment by utunga** [comment]
Maybe disable the datepicker when item is indefinite availability?

**Comment by tfwoodroofMCS** [comment]
New comments since recent fixes:

- [ ] Time is displayed incorrectly on Preview screen for 'Indefinitely' available Offers (also applies to 'Whenever' Wants):

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/5f1c3036-46e6-4b1f-bae3-b0c1e53130ed

- [ ] When editing Offers the 'Indefinitely' text is now shown as 'Whenever available', which is appropriate for Wants (see #13):

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/763fd8fd-988b-4c96-ae0a-a20f8c8f7b95)

**Comment by tfwoodroofMCS** [comment]
@yonasbek just commenting here to flag my previous comment with a couple of minor fixes before we can close this one (and #13).

**Comment by tfwoodroofMCS** [comment]
Time is now displayed correctly on Preview screen, but editing Offers still shows the wrong availability text ('Whenever available' rather than 'Indefinitely'):

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/ef06f7fa-ecc0-4757-81bb-79ea3c27f056

**Comment by tfwoodroofMCS** [comment]
Time stamp of entries in My account -> My items has also gone weird:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/d748b6c3-9630-4ce5-bca4-263646709d34)

**Comment by yonasbek** [comment]
Both comments will be addressed in the next pr
