### ISSUE TITLE
Images from categories should be shown during new item / edit item workflow.

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#73]
Per Tom's comment on #33, now that images are coming from categories we should this during the new item / edit item workflow. If only during the confirmation step/s

**Comment by tfwoodroofMCS** [comment]
Workflow now includes a section for 'Default images', but this is empty in both the upload images and preview screens:

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/e0f1b95d-d6b9-4012-875c-8c7b745b455e)

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/a05e2b33-63d6-4316-ae1b-9889156155e6)

**Comment by tfwoodroofMCS** [comment]
Update - this seems to be working now! Moving to 'Done'.
