### ISSUE TITLE
Edit item, and exit to marketplace doesn't refresh marketplace page

### ISSUE THREAD

**Issue by utunga** [CredComSoc/CreditCoopTech#80]
**To reproduce**

- Visit marketplace page
- Go to 'my item's and my profile
- Click an item, go to edit
- Change the image for the item
- Go through preview and then publish 
- Get taken to 'marketplace' after publish

**Actual**
- On the marketplace the item image has not bee updated 

**Expected**
- Any changes should be visible in the marketplace, that's why we go there - to verify it 'worked'

NB 
- It could be that this also happens when creating new items. 
- Also I wonder what other pages have a redirect of this style?

**Comment by tfwoodroofMCS** [comment]
This does now work, but is slow: multiple refreshes are required for both the user who edited the item, and for other users, before the item gallery displays the new image. The intention @utunga suggests - that the editing user is directed to the refreshed Marketplace in which the changes are immediately visible for verification - therefore isn't yet operational.

**Comment by tfwoodroofMCS** [comment]
Note that at the moment, after publishing a new item (rather than editing an existing one) the app redirects to the home screen, rather than the Marketplace - should we change this?

**Comment by utunga** [comment]
I think it makes sense to direct to the marketplace for sure. 

Also, if multiple refreshes are required for the item shows up in the marketplace it feels to me like it isn't fixed at all at least in terms of what is described on this card?

**Comment by tfwoodroofMCS** [comment]
Editing an item does not redirect to the Marketplace, and changes do appear more quickly, but still requires at least one refresh.

Also still need to implement redirect to Marketplace after publishing a completely new item.

**Comment by tfwoodroofMCS** [comment]
This now seems pretty speedy, but the consequence of #108 is that now the user can't verify that the item has been published by looking in the Marketplace! So the redirect (for both edited and new items) needs to be changed to My account -> My items.

**Comment by tfwoodroofMCS** [comment]
Update to previous comment - no longer applicable as reversing #108.
