### ISSUE TITLE
Change error message to buyer for purchase request that violates seller's positive credit limit

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#86]
As observed in first bullet point of [this comment](https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1691577740), the error message that appears when a buyer makes a purchase request that would violate seller's positive credit limit currently reads: 'Unable to complete the transaction'.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/6cfb7401-dca1-42f8-b5ff-e03598fe56fb)

This is not informative enough for the would-be buyer to know why the purchase request can't be completed, or what to do. 

- [x] Change the pop-up header to 'Seller balance too high'.
- [x] Change the message to: 'This purchase request cannot be completed, as it would take `seller username` beyond their positive credit limit. `seller username` has been notified, but please consider following up with them about your intended purchase.'

**Comment by tfwoodroofMCS** [comment]
Consistent with [this comment](https://github.com/CredComSoc/CreditCoopTech/issues/92#issuecomment-1701442232) and [this comment](https://github.com/CredComSoc/CreditCoopTech/issues/112#issuecomment-1701457173), suggest that in the case that some subset of the items in the purchase request could in principle be progressed (i.e. the user had items from multiple sellers in their cart, and some of them would result in violations of seller positive credit limits, whilst the others would not violate other seller limits), then this error message should be displayed as written above, but with all values of `seller username` for which a violation would occur displayed.

This keeps things as simple as possible whilst still giving the user accurate information. We can add more sophisticated responses later.

**Comment by tfwoodroofMCS** [comment]
Functionality now works well, but text now doesn't fit within pop-up (and there is no function to scroll down)!

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/f9573945-1830-48fe-af81-5859037d0ebb)

Suggested fix:

- [ ] (Unrelated to main problem, just a small grammatical change): Change pop-up header to 'Seller balance(s) too high'.
- [ ] Change the main message to: 'Purchase request cannot be completed, as it would take `seller username 1`, `seller username 2` and `seller username 3` beyond their positive credit limit(s). Please consider following up with them.'

**Comment by yonasbek** [comment]
This one is working for I am not sure why it is not working for you one thing i noticed is that if you have two items in the cart and both of the items is one owner it just displays that one item owners name but if the items are from different owners it shows multiple seller username.


![Image](https://github.com/CredComSoc/CreditCoopTech/assets/49316951/3faecaa1-45a9-4be8-b6ff-53685a93cf67)

**Comment by tfwoodroofMCS** [comment]
Incomplete display is probably just due to different screen sizes (I was testing on a Samsung Galaxy S7) - @tom-newman, any thoughts?

The display of either one or multiple usernames that you described is exactly as it should be! Thanks.

The pop-up header text is still incorrect, though - should be 'Seller balance(s) too high'.

**Comment by yonasbek** [comment]
this fixes are done in the pr i sent now
