### ISSUE TITLE
Change notification text to seller for purchase request that violates their positive credit limit

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#88]
As observed in first bullet point of https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1691577740, if a buyer makes a purchase request that violates the would-be seller's positive credit limit, the seller gets a notification that reads: 'You have received a purchase request from `buyer`. Go to My account to approve or decline..'.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/fdc5904c-913c-4332-b5b0-fcf40799210d)

This is misleading, and should be a notification of an intended (but blocked) purchase. 

- [ ] Change text to: '`buyer username` initiated a purchase request with you for `total price` `credit unit`, but this could not be processed as it would have taken you beyond your positive credit limit by `amount` `credit unit`. Please consider following up with `buyer username` about their intended purchase.'

`amount` should be calculated as `total price` - (`positive limit` - `balance`), and assigned a more informative variable name, such as `positive limit excess` (in whatever syntax is consistent with the rest of the code).

**Comment by yonasbek** [comment]
@tfwoodroofMCS There is no code that sends notification to the seller when the limit is to high it just displays the error message. The above notification is for when the transaction is successful. so may be for all the changes before fixing the code to work as normal sent a notification for failed transactions. If not to much trouble can we re test this issue?

**Comment by tfwoodroofMCS** [comment]
Thanks @yonasbek. Will retest as soon as I have a second test user that I'm confident in - as per Telegram message, the balances of testuser and testuser3 both seem to have become dysfunctional (unresponsive to transactions and with 'Credit' stuck on 500).

**Comment by tfwoodroofMCS** [comment]
Have just tested again with 'fresh' users, and can confirm that the seller is no longer receiving a notification (as you say, the notification is for a valid purchase request, but was still being generated in this case).

The fix now is to put in a notification with the text as per above.

**Comment by yonasbek** [comment]
So this task would be to create a new notification for sellers that have high balances. And this would be triggered when a buyer requests to buy an item from that user.

**Comment by tfwoodroofMCS** [comment]
Correct - specifically sellers that have balances that are so high that the purchase would take them over their positive credit limit (and therefore they should get this notification, instead of the option to accept or decline).
