### ISSUE TITLE
Landing screen content didn't load on first sign in

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#9]
When I first logged in on my mobile (Samsung Galaxy S7, /e/ OS, /e/ OS browser), the content on the landing screen did not display - I could only see the page header and the dropdown menu at the right. Reloading fixed the issue, and it did not recur when I logged out and then in again.

**Comment by tfwoodroofMCS** [comment]
Probably being addressed by #77.

**Comment by utunga** [comment]
closing as dupe
