### ISSUE TITLE
Change error message for purchase request that violates buyer's negative credit limit

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#91]
As observed in second bullet point of https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1691577740, the error message that appears when a buyer makes a purchase request that would violate their negative credit limit currently reads: 'You do not have enough credit to make the purchase'.

![signal-2023-08-25-192952](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/bc91f361-3450-4ad3-a6d0-fedd197f8d35)

This is not unhelpful, but could be better.

- [x] Change the pop-up header to 'Insufficient credit'.
- [x] Update main message to: 'You do not have enough credit to request this purchase, as the total price is `total price` `credit unit` and your available credit is `available credit` `credit unit`.'

`available credit` should be calculated as the buyer's `balance` plus the magnitude of their `negative limit`.

**Comment by tfwoodroofMCS** [comment]
NB: relevant question from Yani copied from[ this comment](https://github.com/CredComSoc/CreditCoopTech/issues/92#issuecomment-1700396740): 'if from 2 seller the transaction was successful and from one of the sellers the transaction fails what would be the result?'

My response copied from final paragraph of [this comment](https://github.com/CredComSoc/CreditCoopTech/issues/92#issuecomment-1701442232):

'I think the simplest thing for now is that if the total price of all items (from multiple sellers or not) is greater than the user's available credit, then they should receive the 'Insufficient balance' message. We can work out something more sophisticated (e.g. progress some subset of the items that would keep the user within their credit limit) later on.'

**Comment by tfwoodroofMCS** [comment]
Looks good - only two minor changes are to decapitalise 'credit' in the pop-up header and include the `credit unit` after the amounts. The credit unit is 'pollen', and I believe this is specified in the internationalisation .json (but might also be in another configuration-type file) - @EugeneJoe, do you know where to read this from?

**Comment by utunga** [comment]
fwiw it's available as the $t("org.token") key.. and [specified in en-LCC.json ](https://github.com/CredComSoc/CreditCoopTech/blob/40a625732fe5c622a86a65d23a7fbb1a94f55322/sb.web.app/src/locales/en-LCC.json#L8)
