### ISSUE TITLE
Fix purchase decline functionality

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#94]
As observed in final bullet point of https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1691577740, if a seller declines a purchase request in My account -> Trades -> Purchase requests (screenshot 1), they initially see its status in  updated to 'declined' (screenshot 2), but refreshing or navigating away from and then back to the page results in the request being redisplayed as needing approval or decline (as in screenshot 1).

![signal-2023-08-25-190734](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/ac10c35a-c3aa-456a-a148-54cc8308c3a1)

![signal-2023-08-25-190715](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/b02671d0-055b-41ee-8706-40c1d1162235)

This suggests to the seller that their decline action didn't work (even though it does - the would-be buyer receives a 'declined' notification, and neither's balances change).

- [x] The request should disappear from the Purchase requests section after navigating away from or refreshing the page.
- [x] Although the buyer does get a notification that their purchase request has been declined, it is still displayed in their Pending Purchases - needs to be removed.
- [x] Low priority: create a record of the request in the Sales History section (with a note of its 'declined' status) [created issue #114 for this in mañana].

**Comment by yonasbek** [comment]
the data endpoint is slow that is why it stays there. and the second one will need a new mechanism of handling it which will need a change in the data base in the backend and also front end so it should have its own issue possibly a in the "manana section"
@tom-newman suggestions

**Comment by tfwoodroofMCS** [comment]
Just tested this again with 'fresh' users, and can confirm that the options don't disappear.

It's also possible to subsequently approve a request after declining it, and the transaction workflow completes (i.e. the buyer gets another notification, this time saying that the request has been approved, and balances update). Although this won't be possible once the decline functionality has been fixed (i.e. the approve/decline options are no longer redisplayed after declining), it does suggest that the status of the transaction itself is unaltered by the choice to decline. Whether this is because the decline button currently does *nothing* or because the problem is 'deeper' (e.g. cc-node isn't doing what it should) needs to be investigated.

**Comment by tfwoodroofMCS** [comment]
Note also that although buyer's do get a notification that their purchase request has been declined, it is still displayed in their Pending Purchases.

**Comment by tfwoodroofMCS** [comment]
Working beautifully now!
