### ISSUE TITLE
Fix acknowledgement of pending purchase requests

### ISSUE THREAD

**Issue by tfwoodroofMCS** [CredComSoc/CreditCoopTech#96]
As observed in final bullet point of https://github.com/CredComSoc/CreditCoopTech/issues/35#issuecomment-1691577740, when a buyer completes a valid purchase request, a whole load of Swedish ('Du har väntande köp som ska...') appears under My account -> Trades -> Pending Purchases.

![Image](https://github.com/CredComSoc/CreditCoopTech/assets/105865183/ffb9734b-351b-4603-8a83-dd9134a3a75d)

This is a useful message, but:

- [x] The Swedish needs to be replaced with 'You have pending purchases that must be approved by the seller(s) before they are completed. You will receive notification(s) when they have approved or declined the purchase(s).' 
- [x] It remains even after the seller declines the purchase (see also #94), but it should be removed (note that it does disappear automatically if the seller approves the request).

**Comment by tfwoodroofMCS** [comment]
Can't review a lot of the other issues before this has been fixed - please prioritise!

**Comment by tfwoodroofMCS** [comment]
Trading History also seems to have vanished for all users.

**Comment by tfwoodroofMCS** [comment]
Approving requests works fine again, Trading History is back, and the message is now in English, but declining purchase requests still doesn't function: the message to the seller doesn't disappear (see video below), and although the buyer gets a notification of the decline, the request is still displayed in their Pending Purchases.

https://github.com/CredComSoc/CreditCoopTech/assets/105865183/a63fdbd8-10d3-4f16-8be1-919b6cd37011

**Comment by yonasbek** [comment]
yes it will be fixed when the new cc-node is up and running
